LangString addOrReinstall ${LANG_ENGLISH} "Update or reinstall Cliply"
LangString alreadyInstalled ${LANG_ENGLISH} "Existing installation detected"
LangString alreadyInstalledLong ${LANG_ENGLISH} "Cliply ${VERSION} is already installed on this computer. Continuing will update the application files without changing clipboard history or application settings."
LangString appRunning ${LANG_ENGLISH} "Cliply is running. Please close it before continuing."
LangString appRunningOkKill ${LANG_ENGLISH} "Cliply is running.$\nSelect OK to close Cliply and continue."
LangString chooseMaintenanceOption ${LANG_ENGLISH} "Select an operation."
LangString choowHowToInstall ${LANG_ENGLISH} "Select how to handle the existing Cliply installation."
LangString createDesktop ${LANG_ENGLISH} "Create desktop shortcut"
LangString dontUninstall ${LANG_ENGLISH} "Update and keep existing data"
LangString dontUninstallDowngrade ${LANG_ENGLISH} "Keep current version"
LangString failedToKillApp ${LANG_ENGLISH} "Could not close Cliply automatically. Please close it and try again."
LangString installingWebview2 ${LANG_ENGLISH} "Installing WebView2 Runtime..."
LangString newerVersionInstalled ${LANG_ENGLISH} "A newer version of Cliply is already installed. To install an older version, uninstall the current version first."
LangString older ${LANG_ENGLISH} "older"
LangString olderOrUnknownVersionInstalled ${LANG_ENGLISH} "An $R4 version of Cliply is installed. Continuing will update the application files without changing clipboard history or application settings."
LangString silentDowngrades ${LANG_ENGLISH} "Silent downgrades are not supported. Please use the graphical installer.$\n"
LangString unableToUninstall ${LANG_ENGLISH} "Unable to uninstall. Please close Cliply and try again."
LangString uninstallApp ${LANG_ENGLISH} "Uninstall current version first"
LangString uninstallBeforeInstalling ${LANG_ENGLISH} "Uninstall before installing"
LangString unknown ${LANG_ENGLISH} "unknown"
LangString webview2AbortError ${LANG_ENGLISH} "WebView2 Runtime installation failed. Cliply requires this component. Run the installer again."
LangString webview2DownloadError ${LANG_ENGLISH} "WebView2 download failed: $0"
LangString webview2DownloadSuccess ${LANG_ENGLISH} "WebView2 installer downloaded"
LangString webview2Downloading ${LANG_ENGLISH} "Downloading WebView2 installer..."
LangString webview2InstallError ${LANG_ENGLISH} "WebView2 Runtime installation failed with error code $1"
LangString webview2InstallSuccess ${LANG_ENGLISH} "WebView2 Runtime installed"
LangString deleteAppData ${LANG_ENGLISH} "Also delete clipboard history and application settings"
