LangString addOrReinstall ${LANG_SIMPCHINESE} "更新或重新安装 Cliply"
LangString alreadyInstalled ${LANG_SIMPCHINESE} "已检测到现有版本"
LangString alreadyInstalledLong ${LANG_SIMPCHINESE} "此计算机已安装 Cliply ${VERSION}。继续后将更新程序文件，剪贴板历史记录和应用设置不会更改。"
LangString appRunning ${LANG_SIMPCHINESE} "Cliply 正在运行。请退出 Cliply，然后继续安装。"
LangString appRunningOkKill ${LANG_SIMPCHINESE} "Cliply 正在运行。$\n选择“确定”将关闭 Cliply 并继续安装。"
LangString chooseMaintenanceOption ${LANG_SIMPCHINESE} "请选择要执行的操作。"
LangString choowHowToInstall ${LANG_SIMPCHINESE} "请选择现有版本的处理方式。"
LangString createDesktop ${LANG_SIMPCHINESE} "创建桌面快捷方式"
LangString dontUninstall ${LANG_SIMPCHINESE} "更新并保留历史记录与设置"
LangString dontUninstallDowngrade ${LANG_SIMPCHINESE} "保留当前版本"
LangString failedToKillApp ${LANG_SIMPCHINESE} "无法关闭 Cliply。请退出程序后重试。"
LangString installingWebview2 ${LANG_SIMPCHINESE} "正在安装 WebView2 Runtime…"
LangString newerVersionInstalled ${LANG_SIMPCHINESE} "此计算机已安装更高版本的 Cliply。若需安装旧版本，请先卸载当前版本。"
LangString older ${LANG_SIMPCHINESE} "较早"
LangString olderOrUnknownVersionInstalled ${LANG_SIMPCHINESE} "此计算机已安装 Cliply（$R4 版本）。继续后将更新程序文件，剪贴板历史记录和应用设置不会更改。"
LangString silentDowngrades ${LANG_SIMPCHINESE} "静默模式不支持降级安装。请使用图形安装程序。$\n"
LangString unableToUninstall ${LANG_SIMPCHINESE} "无法卸载 Cliply。请退出程序后重试。"
LangString uninstallApp ${LANG_SIMPCHINESE} "卸载当前版本"
LangString uninstallBeforeInstalling ${LANG_SIMPCHINESE} "卸载后安装"
LangString unknown ${LANG_SIMPCHINESE} "未知"
LangString webview2AbortError ${LANG_SIMPCHINESE} "Microsoft Edge WebView2 Runtime 安装失败。Cliply 需要该组件才能运行，请重新运行安装程序。"
LangString webview2DownloadError ${LANG_SIMPCHINESE} "WebView2 安装程序下载失败：$0"
LangString webview2DownloadSuccess ${LANG_SIMPCHINESE} "WebView2 安装程序已下载"
LangString webview2Downloading ${LANG_SIMPCHINESE} "正在下载 WebView2 安装程序…"
LangString webview2InstallError ${LANG_SIMPCHINESE} "WebView2 Runtime 安装失败，错误代码：$1"
LangString webview2InstallSuccess ${LANG_SIMPCHINESE} "WebView2 Runtime 已安装"
LangString deleteAppData ${LANG_SIMPCHINESE} "同时删除剪贴板历史记录和应用设置"
